/**
 * Writes the two files search engines look for before they read anything else.
 *
 *   public/robots.txt    what may be crawled, and where the sitemap is
 *   public/sitemap.xml   every address worth indexing
 *
 * Generated rather than hand-written, so they cannot drift out of step with
 * site.config.mjs. Both land in `public/`, which Vite copies to the root of
 * the built site untouched — so they end up at `/robots.txt` and
 * `/sitemap.xml`, which is the only place a crawler looks for them.
 *
 * Run it yourself with `npm run seo:generate`; the build runs it too.
 */

import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { absolute, DISALLOW, PAGES, SITE_URL } from './site.config.mjs'

const here = dirname(fileURLToPath(import.meta.url))
const publicDir = join(here, '..', 'public')

/** Today, as YYYY-MM-DD. The only date format a sitemap accepts. */
function today() {
  return new Date().toISOString().slice(0, 10)
}

/**
 * Escapes the five characters that are not allowed raw in XML.
 *
 * A URL with an `&` in it — a query string, say — silently breaks the whole
 * sitemap without this, and Search Console reports it as "couldn't fetch"
 * rather than "line 14 is malformed".
 */
function xml(value) {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;')
}

function buildRobots() {
  const lines = [
    '# Generated by seo/generate.mjs — edit seo/site.config.mjs, not this file.',
    '',
    'User-agent: *',
  ]

  for (const path of DISALLOW) lines.push(`Disallow: ${path}`)

  lines.push(
    'Allow: /',
    '',
    '# Where the full list of pages lives. Crawlers check here first.',
    `Sitemap: ${absolute('/sitemap.xml')}`,
    '',
  )

  return lines.join('\n')
}

function buildSitemap() {
  const stamp = today()

  const entries = PAGES.map((page) =>
    [
      '  <url>',
      `    <loc>${xml(absolute(page.path))}</loc>`,
      `    <lastmod>${stamp}</lastmod>`,
      `    <changefreq>${xml(page.changefreq)}</changefreq>`,
      `    <priority>${xml(page.priority.toFixed(1))}</priority>`,
      '  </url>',
    ].join('\n'),
  )

  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!-- Generated by seo/generate.mjs — do not edit by hand. -->',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ...entries,
    '</urlset>',
    '',
  ].join('\n')
}

mkdirSync(publicDir, { recursive: true })
writeFileSync(join(publicDir, 'robots.txt'), buildRobots(), 'utf8')
writeFileSync(join(publicDir, 'sitemap.xml'), buildSitemap(), 'utf8')

console.log(`  [32m✓[39m seo — robots.txt and sitemap.xml written for ${SITE_URL}`)

if (PAGES.length === 1) {
  console.log(
    '    note: one indexable address. See seo/AUDIT.md finding 1 before expecting more.',
  )
}
